# mux_config.yaml
subscribers:
  - name: "Seguridad_BT"
    topic: "/cmd_vel_bt_seguridad"
    timeout: 0.5
    priority: 10  # Prioridad MÁXIMA
  - name: "Control_Nav"
    topic: "/cmd_vel_nav"
    timeout: 0.5
    priority: 5   # Prioridad BAJA
publisher: "/cmd_vel" # El topic real que mueve al robot